language: groovy

jdk:
  - oraclejdk8

git:
  depth: 3

env:
  global:
    secure: fWQ2Qdi9PvjTNX5x2t4mMgeYly0w4HUi++fsecBGJiUcQx+E+j1jLbIevilV10zIpqtZ2tKdQuBAfR2Eard69/D2vc0ZV1HisWgGCbdHKE0fustiikEcyzYV4ORdWKfLaeIoKyuAetRwCPsZokdNYnbNjSjfzVePhgk7efzA1+NNyXoQV/4UjT/ojIsndriXYyveS4mda7iNwYxh57+m0Zv3ZqopKcWqmAnoc2q0XTw/Emf7/bpA33pXXhSV2l7VKvkjqMYvkLxre1DAqvlFO2NRPEkw4aepL8TBcVUL26fqHNYu+cCXtv7eoNSSaGAenEzyYraPwzGj7Sic8NCC6fnrbEoxIzgIAd2RvX37AXMxzEuYMjxj+tO58NJN//AQ0cYKS4OtqwGAX0z2hoXs01XgPTvWbu18Eq8T+vBE95oukBSk3NM+7+ITC1PzvyyhmJeMNIpzSBaaVfjMqjC2WCXRCjRzQ55O/s3PyBVG/QQ8nK2nb9r3oM/CMqg+t1uTIE4GcoXR3fc6ATb8OBXnAofjr3eCtmjcBayzVE9urmpshNTz30deGeJSnthsUpQrUBnupRKmOeKh7OdakXrF0bcJb2czXTYKkhABUgVliT6WMM4pAW78UFN9Op2mbfnTl4tIAj4eUt+ASTONgAT/PgsW/Y+danQKRN8bzdUlAS0=

install: true

before_script:
  # set timezone so generated docs have time local to me
  - export TZ=America/New_York
  # disable all the download info and artifcat update checking logging to make log easier to read through
  - echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dorg.slf4j.simpleLogger.log.org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager=warn'" > ~/.mavenrc
  # display some info I like to see in log
  - ./mvnw -B -e -V buildplan:list-phase versions:display-dependency-updates versions:display-plugin-updates versions:display-property-updates

script:
  - ./mvnw -B -e verify

after_success:
  # check with sputnik
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
  # generate and upload coverage report
  - ./mvnw -B -e clean -Dcobertura.report.format=xml cobertura:cobertura && bash <(curl -s https://codecov.io/bash)
  # if is master branch and not a pull request, deploy site to github
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then ./mvnw -B -e clean -Dgithub.global.oauth2Token=$GITHUB_AUTH_TOKEN site-deploy; fi
