language: groovy

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
